### ISSUE TITLE
Rename Production section

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugins#20]
I propose to rename this to `Official`. `Production` implies that the plugins under `Unofficial` are't ready for production.

1/5 on the name `Official`
3/5 that `Production` is a bad name.

From https://github.com/mattermost/mattermost-plugins/pull/19#discussion_r253476031

**Comment by harshilsharma63** [comment]
Or maybe `By Mattermost` and `3rd Party Plugins`? This will also remove any negative aspect of the term "unofficial".

**Comment by hanzei** [comment]
I really like it because it's not judging the plugins and rather just states who wrote them.

@jasonblais What you think about the above proposal?

**Comment by jasonblais** [comment]
I can see the negative connotation of the term "Unofficial" and on the implication of the term "Production".

That said, all Mattermost plugins aren't necessarily official (or production quality) and community-built plugins could be considered official in future - or at least "certified".

Wondering if [Integrations Certification Program](https://docs.google.com/document/d/1nfGuGadJcEFeyxVNy3ytQcn5RXFVC3Z5SS0jMZHFMg0/edit#heading=h.8j2sdydl179) I'm working on would help? It would apply to all plugins and integrations, whether built by Mattermost or not.

**Comment by hanzei** [comment]
Surely. The Integrations Certification Program is great to generate trust in plugins.

But to me this issue is about a short term solution for this repository. In the long term https://integrations.mattermost.com/ and the Integrations Certification Program will fix this problem.

**Comment by jasonblais** [comment]
How about "Certified" vs "Uncertified"? That would mimic the eventual certification program.

I'd also be curious to know whether people find plugins via integrations.mattermost.com or via this repo.

**Comment by hanzei** [comment]
> How about "Certified" vs "Uncertified"? That would mimic the eventual certification program.

Just to be clear: Currently no plugin listed would be in the "Certified" category, right?

**Comment by jasonblais** [comment]
We do say that currently in the README for the "Production" plugins.

> Certified by the Mattermost team, and tested prior to each Mattermost server release.

That said, I'm looking at the purpose of this project, which is to list plugins built by Mattermost staff and community. So I'm wondering if just a single list of `Plugins built by Mattermost staff and community` is sufficient for the purpose of this project. Removes ambiguity.

**Comment by harshilsharma63** [comment]
I'm also not sure about the purpose of this repository. I mean we already have ()[http://integrations.mattermost.com/], right?

**Comment by crspeller** [comment]
Repository no longer active. https://github.com/mattermost/mattermost-plugins/pull/33
