### ISSUE TITLE
Add `mattermost-plugin-tableflip` to plugins list

### ISSUE THREAD

**Issue by cmeadows** [mattermost/mattermost-plugins#28]
I tried adding submitting a Pull Request with my plugin, but I was unable to do so due to permissions.

Please add the following to the list of Unofficial plugins:

`- [mattermost-plugin-tableflip](https://github.com/cmeadows/mattermost-plugin-tableflip)`

**Comment by hanzei** [comment]
Surely. I created #29 for you.

Thanks for creating and submitting this plugins! :tada:
