### ISSUE TITLE
should we archive this repo?

### ISSUE THREAD

**Issue by cpanato** [mattermost/mattermost-plugins#34]

**Comment by cpanato** [comment]
make it readonly

**Comment by jasonblais** [comment]
@hanzei proposed keeping the repo up, see what feedback we get and maybe archive in a few months.

https://github.com/mattermost/mattermost-plugins/pull/33#pullrequestreview-232160820

**Comment by cpanato** [comment]
sounds good, will archive in the 2-3 months
